### ISSUE TITLE
Utilizzare la Dance Mat con l'adattatore Wii U per controller Gamecube

### ISSUE THREAD

**Issue by AnthonyRyuki** [Special-Niewbie/Nintendont-CrisMMMod#5]
Con questa pull request che è stata fatta nella pagina del Nintendont originale si può fare: https://github.com/FIX94/Nintendont/pull/805/

**Comment by Special-Niewbie** [comment]
Sembra che non sia stato testato , o sbaglio? Posso includerla nel kernel senza problemi, ma non so' se dara' altri tipi di problemi. Perche' e' stato scritto il codice, ma sembra che non si sa bene se quello che e' stato scritto poi non andra' ad incasinare altro. Hai l'assoluta certezza che funzioni ;) ?

**Comment by AnthonyRyuki** [comment]
Sinceramente non ho una dance mat, quindi non sono in grado di vedere se funziona, potresti provare a chiedere in quella pull request...

**Comment by geogolem** [comment]
it works. i use it.. i need to update the branch though (rebase) which i will do now.
