### ISSUE TITLE
IPL con due sfondi

### ISSUE THREAD

**Issue by AnthonyRyuki** [Special-Niewbie/Nintendont-CrisMMMod#7]
Quando si cerca di caricare un vero IPL e lo sfondo di caricamento è diverso da quello principale, si creano dei problemi.
Se si cerca di caricare un gioco per GC, il programma si pianta subito, senza neanche passare allo sfondo di caricamento.
Se si cerca di caricare un gioco per Triforce, lo sfondo di caricamento si apre, ma senza mostrare messaggi e senza interrompere la musica di sottofondo durante l'animazione GC, anche se poi il gioco parte. Questo problema si manifesta anche se l'opzione Skip IPL è Off ma non c'è un file IPL, in entrambi i casi.

Ho idea che il problema sia causato dalla RAM del Wii che non è sufficiente per contenere tutti questi dati. Mi sembra infatti che questi problemi non ci fossero prima dell'introduzione della musica di sottofondo.

**Comment by Special-Niewbie** [comment]
Potrebbe essere anche perché da problemi con il download, è il buffer della Wii. Faccio qualche test per cercare di risolverlo. Grazie tante 😉

**Comment by Special-Niewbie** [comment]
Aspetta, quello che mi descrivi tu e' che la musica continua dopo aver premuto sulla lista dei giochi....E questo non dovrebbe accadare. La musica una volta selezionato il gioco si deve fermare, perche' hai questo problema?
Sto testando.... 
1) Con Skip IPL su NO mi fa vedere il boot del GC e poi mi parte il gioco GC tranquillamente.
2) Con Slip IPL su YES non mi fa vedere il GC boot e poi il gioco
